server:
  port: 8761
spring:
  profiles: eureka-o
  security:
    user:
      name: test
      password: dingli
  application:
    name: eureka-o
  
eureka:
  instance:
    hostname: eureka-one
    prefer-ip-address: true
    appname: eureka-one
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-two:8762/eureka/
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 清理服务器
    eviction-interval-timer-in-ms: 5000
---
server:
  port: 8762
spring:
  profiles: eureka-t
  security:
    user:
      name: test
      password: dingli
  application:
    name: eureka-t
eureka:
  instance:
    hostname: eureka-two
    prefer-ip-address: true
    appname: eureka-two
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-one:8761/eureka/
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 清理服务器
    eviction-interval-timer-in-ms: 5000
