server:
  port: 12345
  undertow:
    threads:
      io: 200
      worker: 400
spring:
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: baiyang521
    hikari:
      minimum-idle: 5
      maximum-pool-size: 200
      auto-commit: true
      pool-name: my-test-hikari-pool
      connection-timeout: 10000
      connection-init-sql: select 1
  jackson:
    time-zone: Asia/Shanghai